version: '3.5'
services:
  api01: &app
    image: hiroshimorowaka/rinha-backend-2024:latest
    # build: .
    hostname: api01
    environment:
      - DATABASE_URL=postgres://docker:docker@postgres:5432/rinha
      - CREATE_TABLE=true
    expose:
      - "8080"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '200MB'

  api02:
    <<: *app
    hostname: api02
    environment:
      - DATABASE_URL=postgres://docker:docker@postgres:5432/rinha
      - CREATE_TABLE=false


  postgres:
    image: postgres:16.1-alpine3.19
    command: postgres -c 'max_connections=75' -c 'log_error_verbosity=terse'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rinha
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '100MB'

  nginx:
    image: nginx:1.25.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '50MB'

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
