version: "3.5"

services:
  api01: &api
    image: gldmelo/rinhabackendcrebito:1.2
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - PORT=8080
    ports:
      - "3001:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "120MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - PORT=8080
    ports:
      - "3002:8080"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "60MB"
    
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres.conf:/docker-entrypoint-initdb.d/postgresql.conf
    #command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "250MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
