version: '3.5'
services:
  db:
    image: postgres:latest
    hostname: db
    command: 'postgres -c shared_buffers=256MB -c fsync=off -c full_page_writes=off -c max_connections=1000'
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '220MB'
  api01:
    container_name: rinha-api01
    image: guilhermesouzaaraujo/rinha-api-2024-q1:latest
    depends_on:
      - db
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '75MB'
  api02:
    container_name: rinha-api02
    image: guilhermesouzaaraujo/rinha-api-2024-q1:latest
    depends_on:
      - db
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '75MB'
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '180MB'
networks:
  default:
    driver: bridge
    name: rinha
